<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="fe-github-palettes mb-5">

    <form method="post">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">

        <hr/>
        <h4><?= I18N::translate('Palettes') ?></h4>

         <!-- DEFAULT PALETTE -->
         <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="palette">
                <?= I18N::translate('Default color palette') ?>
            </label>
            <div class="col-sm-9">
                <?= view('components/select', ['name' => 'palette', 'selected' => $palette, 'options' => $palettes]) ?>
            </div>
        </div>

        <!-- SAVE BUTTON -->
        <hr/>
        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('save') ?>
        </button>
    </form>
</div>
